
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20150930 (SVN rev 66)
//----------------------------------------------------

package syntactic_analyzer;

/** CUP generated interface containing symbol constants. */
public interface LexicalClass {
  /* terminals */
  public static final int MULT = 32;
  public static final int CHAR = 48;
  public static final int GE = 41;
  public static final int DOUBLEKW = 17;
  public static final int DOUBLE = 50;
  public static final int SWITCHKW = 13;
  public static final int ASSIGNSYM = 15;
  public static final int WHILEKW = 9;
  public static final int INT = 49;
  public static final int OPENPAR = 21;
  public static final int AND = 42;
  public static final int SEMICOLON = 29;
  public static final int LT = 38;
  public static final int OR = 43;
  public static final int COMMA = 28;
  public static final int PRIVATEKW = 6;
  public static final int FORKW = 10;
  public static final int DIV = 33;
  public static final int CASEKW = 14;
  public static final int DOT = 27;
  public static final int CLOSEPAR = 22;
  public static final int STRINGKW = 20;
  public static final int LE = 40;
  public static final int VOIDKW = 7;
  public static final int IFKW = 11;
  public static final int ELSEKW = 12;
  public static final int DIST = 35;
  public static final int EOF = 0;
  public static final int MAINKW = 2;
  public static final int NEWKW = 4;
  public static final int error = 1;
  public static final int PUBLICKW = 5;
  public static final int BOOLVAL = 47;
  public static final int CLOSEBRACKET = 26;
  public static final int ADD = 30;
  public static final int MOD = 34;
  public static final int EQ = 36;
  public static final int CHARKW = 19;
  public static final int BOOLKW = 18;
  public static final int CLASSKW = 3;
  public static final int NEG = 37;
  public static final int OPENBRACKET = 25;
  public static final int CLASSNAMESTR = 45;
  public static final int CLOSEBRACE = 24;
  public static final int SUBS = 31;
  public static final int OPENBRACE = 23;
  public static final int STRING = 46;
  public static final int INTKW = 16;
  public static final int RETURNKW = 8;
  public static final int GT = 39;
  public static final int IDENTIFIER = 44;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "MAINKW",
  "CLASSKW",
  "NEWKW",
  "PUBLICKW",
  "PRIVATEKW",
  "VOIDKW",
  "RETURNKW",
  "WHILEKW",
  "FORKW",
  "IFKW",
  "ELSEKW",
  "SWITCHKW",
  "CASEKW",
  "ASSIGNSYM",
  "INTKW",
  "DOUBLEKW",
  "BOOLKW",
  "CHARKW",
  "STRINGKW",
  "OPENPAR",
  "CLOSEPAR",
  "OPENBRACE",
  "CLOSEBRACE",
  "OPENBRACKET",
  "CLOSEBRACKET",
  "DOT",
  "COMMA",
  "SEMICOLON",
  "ADD",
  "SUBS",
  "MULT",
  "DIV",
  "MOD",
  "DIST",
  "EQ",
  "NEG",
  "LT",
  "GT",
  "LE",
  "GE",
  "AND",
  "OR",
  "IDENTIFIER",
  "CLASSNAMESTR",
  "STRING",
  "BOOLVAL",
  "CHAR",
  "INT",
  "DOUBLE"
  };
}

